# Słownik haseł do gry Kalambury Zuzanny
# 300 haseł podzielonych na 3 poziomy trudności (100 na każdy)
# Każdy poziom ma 5 kategorii po 20 haseł

WORDS = {
    "easy": [
        # ===== FILMY I SERIALE (20) =====
        {"word": "Batman", "category": "Filmy i Seriale"},
        {"word": "Superman", "category": "Filmy i Seriale"},
        {"word": "Shrek", "category": "Filmy i Seriale"},
        {"word": "Kraina Lodu", "category": "Filmy i Seriale"},
        {"word": "Titanic", "category": "Filmy i Seriale"},
        {"word": "Avatar", "category": "Filmy i Seriale"},
        {"word": "Szczęki", "category": "Filmy i Seriale"},
        {"word": "Rocky", "category": "Filmy i Seriale"},
        {"word": "Rambo", "category": "Filmy i Seriale"},
        {"word": "Terminator", "category": "Filmy i Seriale"},
        {"word": "Matrix", "category": "Filmy i Seriale"},
        {"word": "Joker", "category": "Filmy i Seriale"},
        {"word": "Spiderman", "category": "Filmy i Seriale"},
        {"word": "Hulk", "category": "Filmy i Seriale"},
        {"word": "Thor", "category": "Filmy i Seriale"},
        {"word": "Iron Man", "category": "Filmy i Seriale"},
        {"word": "Pinokio", "category": "Filmy i Seriale"},
        {"word": "Nemo", "category": "Filmy i Seriale"},
        {"word": "Simba", "category": "Filmy i Seriale"},
        {"word": "Elsa", "category": "Filmy i Seriale"},
        
        # ===== ZWIERZĘTA (20) =====
        {"word": "Pies", "category": "Zwierzęta"},
        {"word": "Kot", "category": "Zwierzęta"},
        {"word": "Lew", "category": "Zwierzęta"},
        {"word": "Słoń", "category": "Zwierzęta"},
        {"word": "Żyrafa", "category": "Zwierzęta"},
        {"word": "Małpa", "category": "Zwierzęta"},
        {"word": "Krokodyl", "category": "Zwierzęta"},
        {"word": "Rekin", "category": "Zwierzęta"},
        {"word": "Delfin", "category": "Zwierzęta"},
        {"word": "Orzeł", "category": "Zwierzęta"},
        {"word": "Koń", "category": "Zwierzęta"},
        {"word": "Krowa", "category": "Zwierzęta"},
        {"word": "Świnia", "category": "Zwierzęta"},
        {"word": "Kura", "category": "Zwierzęta"},
        {"word": "Kaczka", "category": "Zwierzęta"},
        {"word": "Królik", "category": "Zwierzęta"},
        {"word": "Mysz", "category": "Zwierzęta"},
        {"word": "Wąż", "category": "Zwierzęta"},
        {"word": "Żaba", "category": "Zwierzęta"},
        {"word": "Ryba", "category": "Zwierzęta"},
        
        # ===== ZAWODY (20) =====
        {"word": "Lekarz", "category": "Zawody"},
        {"word": "Policjant", "category": "Zawody"},
        {"word": "Strażak", "category": "Zawody"},
        {"word": "Nauczyciel", "category": "Zawody"},
        {"word": "Kucharz", "category": "Zawody"},
        {"word": "Kierowca", "category": "Zawody"},
        {"word": "Pilot", "category": "Zawody"},
        {"word": "Fryzjer", "category": "Zawody"},
        {"word": "Dentysta", "category": "Zawody"},
        {"word": "Aktor", "category": "Zawody"},
        {"word": "Piłkarz", "category": "Zawody"},
        {"word": "Piosenkarz", "category": "Zawody"},
        {"word": "Malarz", "category": "Zawody"},
        {"word": "Mechanik", "category": "Zawody"},
        {"word": "Sprzedawca", "category": "Zawody"},
        {"word": "Kelner", "category": "Zawody"},
        {"word": "Ogrodnik", "category": "Zawody"},
        {"word": "Listonosz", "category": "Zawody"},
        {"word": "Murarz", "category": "Zawody"},
        {"word": "Stolarz", "category": "Zawody"},
        
        # ===== JEDZENIE (20) =====
        {"word": "Pizza", "category": "Jedzenie"},
        {"word": "Burger", "category": "Jedzenie"},
        {"word": "Hot dog", "category": "Jedzenie"},
        {"word": "Frytki", "category": "Jedzenie"},
        {"word": "Lody", "category": "Jedzenie"},
        {"word": "Ciasto", "category": "Jedzenie"},
        {"word": "Chleb", "category": "Jedzenie"},
        {"word": "Jajko", "category": "Jedzenie"},
        {"word": "Ser", "category": "Jedzenie"},
        {"word": "Mleko", "category": "Jedzenie"},
        {"word": "Banan", "category": "Jedzenie"},
        {"word": "Jabłko", "category": "Jedzenie"},
        {"word": "Pomarańcza", "category": "Jedzenie"},
        {"word": "Arbuz", "category": "Jedzenie"},
        {"word": "Truskawka", "category": "Jedzenie"},
        {"word": "Kurczak", "category": "Jedzenie"},
        {"word": "Zupa", "category": "Jedzenie"},
        {"word": "Makaron", "category": "Jedzenie"},
        {"word": "Kanapka", "category": "Jedzenie"},
        {"word": "Czekolada", "category": "Jedzenie"},
        
        # ===== SŁAWNI (20) =====
        {"word": "Michael Jackson", "category": "Sławni"},
        {"word": "Elvis Presley", "category": "Sławni"},
        {"word": "Madonna", "category": "Sławni"},
        {"word": "Ronaldo", "category": "Sławni"},
        {"word": "Messi", "category": "Sławni"},
        {"word": "Mickey Mouse", "category": "Sławni"},
        {"word": "Kaczor Donald", "category": "Sławni"},
        {"word": "Harry Potter", "category": "Sławni"},
        {"word": "Sherlock Holmes", "category": "Sławni"},
        {"word": "James Bond", "category": "Sławni"},
        {"word": "Mona Lisa", "category": "Sławni"},
        {"word": "Einstein", "category": "Sławni"},
        {"word": "Newton", "category": "Sławni"},
        {"word": "Kleopatra", "category": "Sławni"},
        {"word": "Napoleon", "category": "Sławni"},
        {"word": "Mozart", "category": "Sławni"},
        {"word": "Beethoven", "category": "Sławni"},
        {"word": "Picasso", "category": "Sławni"},
        {"word": "Van Gogh", "category": "Sławni"},
        {"word": "Leonardo da Vinci", "category": "Sławni"},
    ],
    
    "medium": [
        # ===== FILMY I SERIALE (20) =====
        {"word": "Incepcja", "category": "Filmy i Seriale"},
        {"word": "Interstellar", "category": "Filmy i Seriale"},
        {"word": "Gladiator", "category": "Filmy i Seriale"},
        {"word": "Braveheart", "category": "Filmy i Seriale"},
        {"word": "Forrest Gump", "category": "Filmy i Seriale"},
        {"word": "Pulp Fiction", "category": "Filmy i Seriale"},
        {"word": "Fight Club", "category": "Filmy i Seriale"},
        {"word": "Deadpool", "category": "Filmy i Seriale"},
        {"word": "Venom", "category": "Filmy i Seriale"},
        {"word": "Thanos", "category": "Filmy i Seriale"},
        {"word": "Yoda", "category": "Filmy i Seriale"},
        {"word": "Chewbacca", "category": "Filmy i Seriale"},
        {"word": "Gollum", "category": "Filmy i Seriale"},
        {"word": "Gandalf", "category": "Filmy i Seriale"},
        {"word": "Voldemort", "category": "Filmy i Seriale"},
        {"word": "Daenerys", "category": "Filmy i Seriale"},
        {"word": "Jon Snow", "category": "Filmy i Seriale"},
        {"word": "Walter White", "category": "Filmy i Seriale"},
        {"word": "Dexter", "category": "Filmy i Seriale"},
        {"word": "Hannibal", "category": "Filmy i Seriale"},
        
        # ===== ZWIERZĘTA (20) =====
        {"word": "Koala", "category": "Zwierzęta"},
        {"word": "Panda", "category": "Zwierzęta"},
        {"word": "Pingwin", "category": "Zwierzęta"},
        {"word": "Leniwiec", "category": "Zwierzęta"},
        {"word": "Surykatka", "category": "Zwierzęta"},
        {"word": "Fretka", "category": "Zwierzęta"},
        {"word": "Alpaka", "category": "Zwierzęta"},
        {"word": "Lama", "category": "Zwierzęta"},
        {"word": "Jeleń", "category": "Zwierzęta"},
        {"word": "Łoś", "category": "Zwierzęta"},
        {"word": "Borsuk", "category": "Zwierzęta"},
        {"word": "Wydra", "category": "Zwierzęta"},
        {"word": "Foka", "category": "Zwierzęta"},
        {"word": "Mors", "category": "Zwierzęta"},
        {"word": "Narwal", "category": "Zwierzęta"},
        {"word": "Lemur", "category": "Zwierzęta"},
        {"word": "Tapir", "category": "Zwierzęta"},
        {"word": "Kojot", "category": "Zwierzęta"},
        {"word": "Szakal", "category": "Zwierzęta"},
        {"word": "Hiena", "category": "Zwierzęta"},
        
        # ===== ZAWODY (20) =====
        {"word": "Chirurg", "category": "Zawody"},
        {"word": "Psycholog", "category": "Zawody"},
        {"word": "Architekt", "category": "Zawody"},
        {"word": "Programista", "category": "Zawody"},
        {"word": "Prawnik", "category": "Zawody"},
        {"word": "Sędzia", "category": "Zawody"},
        {"word": "Dyplomata", "category": "Zawody"},
        {"word": "Archeolog", "category": "Zawody"},
        {"word": "Geolog", "category": "Zawody"},
        {"word": "Astronom", "category": "Zawody"},
        {"word": "Tancerz", "category": "Zawody"},
        {"word": "Reżyser", "category": "Zawody"},
        {"word": "Scenarzysta", "category": "Zawody"},
        {"word": "Kaskader", "category": "Zawody"},
        {"word": "Magik", "category": "Zawody"},
        {"word": "Akrobata", "category": "Zawody"},
        {"word": "Zegarmistrz", "category": "Zawody"},
        {"word": "Jubiler", "category": "Zawody"},
        {"word": "Tatuażysta", "category": "Zawody"},
        {"word": "Barista", "category": "Zawody"},
        
        # ===== JEDZENIE (20) =====
        {"word": "Sushi", "category": "Jedzenie"},
        {"word": "Ramen", "category": "Jedzenie"},
        {"word": "Pierogi", "category": "Jedzenie"},
        {"word": "Bigos", "category": "Jedzenie"},
        {"word": "Paella", "category": "Jedzenie"},
        {"word": "Risotto", "category": "Jedzenie"},
        {"word": "Carbonara", "category": "Jedzenie"},
        {"word": "Tiramisu", "category": "Jedzenie"},
        {"word": "Croissant", "category": "Jedzenie"},
        {"word": "Bagietka", "category": "Jedzenie"},
        {"word": "Hummus", "category": "Jedzenie"},
        {"word": "Falafel", "category": "Jedzenie"},
        {"word": "Kebab", "category": "Jedzenie"},
        {"word": "Tacos", "category": "Jedzenie"},
        {"word": "Burrito", "category": "Jedzenie"},
        {"word": "Nachos", "category": "Jedzenie"},
        {"word": "Pad Thai", "category": "Jedzenie"},
        {"word": "Kimchi", "category": "Jedzenie"},
        {"word": "Tofu", "category": "Jedzenie"},
        {"word": "Tempura", "category": "Jedzenie"},
        
        # ===== SŁAWNI (20) =====
        {"word": "Freddie Mercury", "category": "Sławni"},
        {"word": "David Bowie", "category": "Sławni"},
        {"word": "Prince", "category": "Sławni"},
        {"word": "Beyonce", "category": "Sławni"},
        {"word": "Rihanna", "category": "Sławni"},
        {"word": "Drake", "category": "Sławni"},
        {"word": "Eminem", "category": "Sławni"},
        {"word": "Snoop Dogg", "category": "Sławni"},
        {"word": "Kanye West", "category": "Sławni"},
        {"word": "Ed Sheeran", "category": "Sławni"},
        {"word": "Salvador Dali", "category": "Sławni"},
        {"word": "Andy Warhol", "category": "Sławni"},
        {"word": "Banksy", "category": "Sławni"},
        {"word": "Szekspir", "category": "Sławni"},
        {"word": "Hemingway", "category": "Sławni"},
        {"word": "Tolkien", "category": "Sławni"},
        {"word": "Stephen King", "category": "Sławni"},
        {"word": "Agatha Christie", "category": "Sławni"},
        {"word": "Marilyn Monroe", "category": "Sławni"},
        {"word": "Audrey Hepburn", "category": "Sławni"},
    ],
    
    "hard": [
        # ===== FILMY I SERIALE (20) =====
        {"word": "Memento", "category": "Filmy i Seriale"},
        {"word": "Mulholland Drive", "category": "Filmy i Seriale"},
        {"word": "Eraserhead", "category": "Filmy i Seriale"},
        {"word": "Solaris", "category": "Filmy i Seriale"},
        {"word": "Nosferatu", "category": "Filmy i Seriale"},
        {"word": "Metropolis", "category": "Filmy i Seriale"},
        {"word": "Akira", "category": "Filmy i Seriale"},
        {"word": "Paprika", "category": "Filmy i Seriale"},
        {"word": "Perfect Blue", "category": "Filmy i Seriale"},
        {"word": "Midsommar", "category": "Filmy i Seriale"},
        {"word": "Dziedzictwo", "category": "Filmy i Seriale"},
        {"word": "Anihilacja", "category": "Filmy i Seriale"},
        {"word": "Nowy początek", "category": "Filmy i Seriale"},
        {"word": "Łowca androidów", "category": "Filmy i Seriale"},
        {"word": "Donnie Darko", "category": "Filmy i Seriale"},
        {"word": "Miasto ciemności", "category": "Filmy i Seriale"},
        {"word": "Brazil", "category": "Filmy i Seriale"},
        {"word": "Primer", "category": "Filmy i Seriale"},
        {"word": "Moon", "category": "Filmy i Seriale"},
        {"word": "Ex Machina", "category": "Filmy i Seriale"},
        
        # ===== ZWIERZĘTA (20) =====
        {"word": "Quokka", "category": "Zwierzęta"},
        {"word": "Axolotl", "category": "Zwierzęta"},
        {"word": "Okapi", "category": "Zwierzęta"},
        {"word": "Aye-aye", "category": "Zwierzęta"},
        {"word": "Pangolin", "category": "Zwierzęta"},
        {"word": "Kakapo", "category": "Zwierzęta"},
        {"word": "Wytrzeszcz", "category": "Zwierzęta"},
        {"word": "Diugoń", "category": "Zwierzęta"},
        {"word": "Sajga", "category": "Zwierzęta"},
        {"word": "Mandryl", "category": "Zwierzęta"},
        {"word": "Kapibara", "category": "Zwierzęta"},
        {"word": "Tuszkanczyk", "category": "Zwierzęta"},
        {"word": "Kinkażu", "category": "Zwierzęta"},
        {"word": "Potoo", "category": "Zwierzęta"},
        {"word": "Hoatzin", "category": "Zwierzęta"},
        {"word": "Fossa", "category": "Zwierzęta"},
        {"word": "Binturong", "category": "Zwierzęta"},
        {"word": "Gharial", "category": "Zwierzęta"},
        {"word": "Gekon", "category": "Zwierzęta"},
        {"word": "Kameleon", "category": "Zwierzęta"},
        
        # ===== ZAWODY (20) =====
        {"word": "Entomolog", "category": "Zawody"},
        {"word": "Kryptograf", "category": "Zawody"},
        {"word": "Somelier", "category": "Zawody"},
        {"word": "Etymolog", "category": "Zawody"},
        {"word": "Numizmatyk", "category": "Zawody"},
        {"word": "Kartograf", "category": "Zawody"},
        {"word": "Paleontolog", "category": "Zawody"},
        {"word": "Egiptolog", "category": "Zawody"},
        {"word": "Ichtiolog", "category": "Zawody"},
        {"word": "Lektor", "category": "Zawody"},
        {"word": "Korektor", "category": "Zawody"},
        {"word": "Kurator", "category": "Zawody"},
        {"word": "Konserwator", "category": "Zawody"},
        {"word": "Mediator", "category": "Zawody"},
        {"word": "Aktuariusz", "category": "Zawody"},
        {"word": "Oceanograf", "category": "Zawody"},
        {"word": "Sejsmolog", "category": "Zawody"},
        {"word": "Wulkanolog", "category": "Zawody"},
        {"word": "Meteorolog", "category": "Zawody"},
        {"word": "Limnolog", "category": "Zawody"},
        
        # ===== JEDZENIE (20) =====
        {"word": "Ceviche", "category": "Jedzenie"},
        {"word": "Gravlax", "category": "Jedzenie"},
        {"word": "Gnocchi", "category": "Jedzenie"},
        {"word": "Focaccia", "category": "Jedzenie"},
        {"word": "Bruschetta", "category": "Jedzenie"},
        {"word": "Carpaccio", "category": "Jedzenie"},
        {"word": "Gazpacho", "category": "Jedzenie"},
        {"word": "Bouillabaisse", "category": "Jedzenie"},
        {"word": "Coq au vin", "category": "Jedzenie"},
        {"word": "Ratatouille", "category": "Jedzenie"},
        {"word": "Bibimbap", "category": "Jedzenie"},
        {"word": "Pho", "category": "Jedzenie"},
        {"word": "Creme Brulee", "category": "Jedzenie"},
        {"word": "Profiterole", "category": "Jedzenie"},
        {"word": "Macaron", "category": "Jedzenie"},
        {"word": "Cannoli", "category": "Jedzenie"},
        {"word": "Baklawa", "category": "Jedzenie"},
        {"word": "Churros", "category": "Jedzenie"},
        {"word": "Mochi", "category": "Jedzenie"},
        {"word": "Edamame", "category": "Jedzenie"},
        
        # ===== SŁAWNI (20) =====
        {"word": "Nietzsche", "category": "Sławni"},
        {"word": "Kierkegaard", "category": "Sławni"},
        {"word": "Schopenhauer", "category": "Sławni"},
        {"word": "Kafka", "category": "Sławni"},
        {"word": "Dostojewski", "category": "Sławni"},
        {"word": "Czechow", "category": "Sławni"},
        {"word": "Borges", "category": "Sławni"},
        {"word": "Marquez", "category": "Sławni"},
        {"word": "Murakami", "category": "Sławni"},
        {"word": "Bułhakow", "category": "Sławni"},
        {"word": "Kurosawa", "category": "Sławni"},
        {"word": "Tarkowski", "category": "Sławni"},
        {"word": "Kubrick", "category": "Sławni"},
        {"word": "Bergman", "category": "Sławni"},
        {"word": "Fellini", "category": "Sławni"},
        {"word": "Godard", "category": "Sławni"},
        {"word": "Truffaut", "category": "Sławni"},
        {"word": "Hitchcock", "category": "Sławni"},
        {"word": "Scorsese", "category": "Sławni"},
        {"word": "Tarantino", "category": "Sławni"},
    ]
}

# Nazwy poziomów trudności po polsku
DIFFICULTY_NAMES = {
    "easy": "Łatwy",
    "medium": "Średni",
    "hard": "Trudny"
}

# Mnożniki punktów dla każdego poziomu
DIFFICULTY_MULTIPLIERS = {
    "easy": 1.0,
    "medium": 1.5,
    "hard": 2.0
}

